### ISSUE TITLE
기술 매니저님 질문

### ISSUE THREAD

**Issue by wisdom08** [wisdom08/Springboot-Blog#15]
안녕하세요 기술매니저님! 
이슈는 제가 어제 과제 제출하고나서 추후 해야할 일들을 정리해봤습니다. 
해당 이슈만 참고해주시면 될 거 같습니다.

과제를 구현하면서 엔티티와 디티오의 설계와 관계에 대해서 궁금했었는데요.
DTO를 어떻게 쓰는 게 좋은 코드인지 궁금합니다. 장현준 매니저님께서 전에 엔티티-디티오 변환은 서비스 계층에서 하는 게 적절하다고 하셨는데 서비스 계층은 비즈니스 로직을 처리하는 곳인데 엔티티-디티오 변환하는 게 비즈니스 로직이라고 할 수 있는지 좀 이해가 잘 안됩니다. 
구글링해서 관련 문서들을 몇 개 읽어보기는 했는데 컨트롤러 계층에서도 하기도 한다는데 그 이유도 잘 납득이 되지는 않고요 🥲 
프로젝트의 규모나 특성에 따라 다르게 적용될 수 있는 부분이고 정답은 없겠지만 이번 주차에 진행하게 되는 크지 않은 소규모의 프로젝트에서는 어떻게 DTO-엔티티 관련 코드를 작성하는 게 적절한지 질문드리고 싶습니다. 
최근에 자바 record 라는 걸 알게 됐는데 record 를 직접 사용해보지는 않았지만 record 로 DTO를 실제로 전부 대체할 수 있는 건지도 궁금합니다. 

그리고 지난주차 피드백에서 setter 보다는 도메인 메서드를 만드는 게 어떻냐고 말씀하셨는데 도메인 메서드가 뭔가요? 구글링해도 나오지 않아서 질문드립니다. 우선 찾아보니 setter 대신 아래 3가지를 쓰는 것 같습니다. 

1. 생성자를 오버로딩
2. Builder 패턴 사용
3. 정적 팩토리 메소드

**Comment by JangHyeonJun2** [comment]
안녕하세요. 지혜님 주말에 일이 있어서 지금 답변을 작성합니다. 
1. 일단 제가 저번에 말씀드린 DTO를 서비스계층에서 사용한다는 말이 조금 와전된거 같습니다. 흠🤔 일단 DTO는 지혜님도 알고계시겠지만, 데이터 자체를 이동시키기 위한 클래스라고 말씀드렸습니다. 그렇기 때문에 `controller`에서 request받은 데이터를 `service layer` 로 이동시킨다. 라고 이해해주시면 될 거 같고 , 위에서 지혜님이 말씀하신 서비스계층에서 사용한다는 말은 `controller`에서 받은 데이터를 서비스계층에서 builder패턴을 사용하여 entity를 만들거나 도메인 entity 생성자를 이용해서 entity를 생성한다거나 이럴때 사용한다 라고 생각해주시면 될 거 같아요. 그렇기 때문에 dto을 가지고 `service layer` 에서 실질적으로 로직을 수행하는 건 없습니다.😊 dto to entity 이런식으로 많이 사용이됩니다.

[정적 펙터리 메서드란?](https://velog.io/@ljinsk3/%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C%EB%8A%94-%EC%99%9C-%EC%82%AC%EC%9A%A9%ED%95%A0%EA%B9%8C)

또한 Spring JPA를 사용하면서 JPQL을 사용할 때가 있는데요. 그때 반환되는 클래스를 respone로 반환되는 경우가 있습니다. 
```java
@Query
(
    "SELECT new com.imaslab.fms.dtos.car.CarBatteryHistoryDTO(CBL.voltage, CBL.isRunning, CBL.creationDateTime, CBL.packetType) " +
    "FROM " +
    "   CarBatteryLog CBL " +
    "WHERE " +
    "   (:carId IS NULL OR CBL.carId = :carId) " +
    "   AND ((:fromDate IS NULL OR :toDate IS NULL) OR CBL.creationDateTime BETWEEN :fromDate AND :toDate) "
)
@Transactional(readOnly=true)
Page<CarBatteryHistoryDTO> fetchCarBatteryHistory(Long carId, LocalDateTime fromDate, LocalDateTime toDate, Pageable pageable);
```
2. recode는 저도 처음 들어보는 내용이랑 조금 더 확인 후 말씀드리겠습니다. 
3. 사실 setter 같은 경우는 객체지향프로그래밍에서 조금 지양하는 패턴중하나입니다. 
쓰지 말라는 게 아닌, 외부에서 아무 제약없이 사용할 수 있는 public Setter를 사용할 때에는 주의하라는 의미입니다. Setter가 아예 없으면 PersistenceContext가 DB에서 가져온 값을 Entity에 주입하는 상황에서 예외가 발생할 수 있습니다.(생성자 주입, Reflective Field Access 주입, Setter 주입이 있는데, Setter가 없으면 Setter 주입 사용시 오류)
JPA에서 Setter는 곧 Update 쿼리를 의미합니다. Setter를 만들면 해당 Setter가 어디에서든지 호출될 수 있으므로 특정 칼럼이 어디에서 수정되었는지 파악하기 힘들고 칼럼을 수정하기 전 검증이 필요한 경우 이를 무시할 수 있기에 무결성이 훼손되는 등의 부작용이 발생할 수 있습니다.
따라서 public Setter를 지양하고 메서드를 별도로 만들어 Update 처리를 OOP스럽게, 통제된 상황에서 쓰는 게 좋다는 의미입니다.
대신 Update 처리가 통제된 상황에서는 Setter를 사용해도 무방합니다.
예를 들어,
```java
@Entity
@Setter
@Getter
public class User {
  ..
  @Column(nullable = false)
  private Integer mileage; // 마일리지(0보다 커야 함)
}
```
이 경우 mileage는 어디서든 Setter로 접근하여 수정할 수 있으므로 잘못된 로직 등에 의해 0 미만의 값이 들어가 무결성이 훼손될 수 있습니다.
```java
@Entity
// @Setter
@Getter
public class User {
  ..
  @Column(nullable = false)
  @Setter(AccessLevel.PROTECTED) // PersistenceContext가 접근하기 위해 필요
  private Integer mileage; // 마일리지(0보다 커야 함)

  public void consumeMileage(int amount) {
    // validation
    if (amount <= 0) {
      throw new InvalidMileageException();
    }
    if (this.mileage < amount) {
      throw new MileageInsufficientException();
    }
    this.mileage -= amount;
  }
}
```
Setter 대신 명확히 '마일리지 사용'이라는 의미를 가진 메서드를 만들어 검증 로직을 넣는 경우 가독성도 향상되고 무결성을 유지할 수 있습니다.
이렇게 이해해주시면 조금 더 좋을 거 같습니다 😊

**Comment by JangHyeonJun2** [comment]
더 궁금하신게 있으시면 답글 달아주세요 :)

**Comment by wisdom08** [comment]
@JangHyeonJun2 네 매니저님 감사합니다. 고민이 좀 해결됐습니다. 

팩토리메서드패턴을 이용하면 생성자는 아래 코드에서처럼 접근제어자를 private 으로 변경할 수 있겠네요.
빈 생성자도 굳이 public 일 필요가 없겠어요.  신기하네요 ㅎㅎ
사실 위에 이슈를 지금 다시보니 너무 구구절절 쓴 거 같은데
중심 이슈는 제가 엔티티 디자인을 어떻게 하는 게 더 좋은 코드인지 좀 고민이 있었던 거 같아요.
정적팩토리메서드패턴을 한번 적용해봐야겠네요.
감사합니다.
```
protected Post() {}

private Post(String title, String content) {
        this.title = title;
        this.content = content;
}

public static Post of(String title, String content) {
        return new Post(title, content);
}
```
